export enum  EditorMenuListKeys{
    UNDO = 'undo',
    REDO = 'redo',
    Add_DDEVICE_TO_CHART = 'add_device',
    FIT = 'fit',
    EDIT_DEVICE='edit_device',
    REMOVE_DEVICE_FROM_CHART = 'remove_device_from_chart',
    DELETE_DEVICE = 'delete_device',
    EDIT_LINE = 'edit_line',
    REMOVE_LINE_FROM_CHART = 'remove_line_from_chart',
    DELETE_LINE = 'delete_line',
    BOND_LINES = 'bond_lines',
    EDIT_PORT = 'edit_port',
    DELETE_PORT = 'delete_port',
    REMOVE_PORT = 'remove_port',
    EDIT_PORTS = 'edit_ports',
    CONNECT_PAIRED_PORTS = 'connect_paired_ports',
    MOVE_HANDLE_TO_LEFT = 'move_handle_to_left',
    MOVE_HANDLE_TO_RIGHT = 'move_handle_to_right',
    MOVE_HANDLE_TO_TOP = 'move_handle_to_top',
    MOVE_HANDLE_TO_BOTTOM = 'move_handle_to_bottom',
    DELETE_NOTE = 'delete_note',
    EDIT_NOTE_COLOR = 'edit_note_color',
    EDIT_BOND = 'edit_bond',
    UNBOND_PORTS = 'unbond_ports',
    REMOVE_BOND_FROM_CHART = 'remove_bond_from_chart',
}